[agent]
  interval = "5s"
  round_interval = true

[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]
  database = "healthcare"

# -------------------------
# Simulated Patient Vitals
# -------------------------
[[inputs.exec]]
  commands = ["python3 /scripts/patient_sim.py"]
  data_format = "influx"
