apiVersion: 1
providers:
  - name: 'Zabbix'
    org_id: 1
    folder: ''
    type: alexanderzobnin-zabbix-app
    options:
      url: 'http://zabbix-web:8080'
      access: proxy
      basicAuth: false
